// Generated by CoffeeScript 1.7.1
(function() {
  var docpadConfig,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  docpadConfig = {
    templateData: {
      site: {
        url: "http://www.mockthetest.com",
        oldUrls: ['mockthetest.herokuapp.com'],
        title: "Mock the Test - free practise and mock test for Life in the UK Test and more.",
        description: "A free and easy to use web app to help you pass the Life in the UK Test.",
        keywords: "Life in the UK Test, UK immigration, UK Settlement",
        author: "Warren Liu",
        email: "admin@mockthetest.com",
        styles: ["/styles/style.css", "/styles/bootstrap-slate.css", "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"],
        scripts: ["//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js", "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js", "/vendor/twitter-bootstrap/dist/js/bootstrap.min.js", "/scripts/script.js"]
      },
      getPreparedTitle: function() {
        if (this.document.title) {
          return "" + this.document.title + " | " + this.site.title;
        } else {
          return this.site.title;
        }
      },
      getPreparedDescription: function() {
        return this.document.description || this.site.description;
      },
      getPreparedKeywords: function() {
        return this.site.keywords.concat(this.document.keywords || []).join(', ');
      }
    },
    collections: {
      pages: function(database) {
        return database.findAllLive({
          pageOrder: {
            $exists: true
          }
        }, [
          {
            pageOrder: 1,
            title: 1
          }
        ]);
      },
      posts: function(database) {
        return database.findAllLive({
          tags: {
            $has: 'post'
          }
        }, [
          {
            date: -1
          }
        ]);
      }
    },
    plugins: {
      downloader: {
        downloads: [
          {
            name: 'Twitter Bootstrap',
            path: 'src/files/vendor/twitter-bootstrap',
            url: 'https://codeload.github.com/twbs/bootstrap/tar.gz/master',
            tarExtractClean: true
          }
        ]
      },
      ghpages: {
          deployRemote: 'target',
          deployBranch: 'master'
      }
    },
    events: {
      serverExtend: function(opts) {
        var docpad, latestConfig, newUrl, oldUrls, server;
        server = opts.server;
        docpad = this.docpad;
        latestConfig = docpad.getConfig();
        oldUrls = latestConfig.templateData.site.oldUrls || [];
        newUrl = latestConfig.templateData.site.url;
        return server.use(function(req, res, next) {
          var _ref;
          if (_ref = req.headers.host, __indexOf.call(oldUrls, _ref) >= 0) {
            return res.redirect(newUrl + req.url, 301);
          } else {
            return next();
          }
        });
      }
    }
  };

  module.exports = docpadConfig;

}).call(this);

//# sourceMappingURL=docpad.map
